### ISSUE TITLE
Responding to your question.

### ISSUE THREAD

**Issue by itsaark** [colasbd/TestPeriscopeKit#1]
Hi,

I just checked your email. By "not working" you mean nothing shows up on screen? or the heart icon is enlarged? I'm no obj-c pro, but I was just checking your code as you suggested.

I don't see any function like `touchesBegan` which triggers the animation.
I also found the following lines of code "might" have something to do with the functionality.

**May I know why you included this code under viewDidLoad?**

``` objective-c
self.heartBubblesScene = [[CBDHeartBubbleScene alloc] initWithSize:self.heartBubbleView.frame.size];
[self.heartBubblesScene setScaleMode:SKSceneScaleModeFill];
self.heartBubblesScene.backgroundColor = [UIColor clearColor];

self.heartBubbleView.allowsTransparency =  #YES;
```

**Why are you initializing the heartBubblesScene here?**  
 `self.heartBubblesScene = [[CBDHeartBubbleScene alloc] initWithSize:self.heartBubbleView.frame.size];`

**Can you try SKSceneScaleModeAspectFit instead?**
 `[self.heartBubblesScene setScaleMode:SKSceneScaleModeFill];`

**Comment by colasbd** [comment]
Thanks @itsaark,
finally it works.

**Comment by itsaark** [comment]
Awesome! What changes did you make?

**Comment by colasbd** [comment]
``` obj-c
self.heartBubblesScene = [[CBDHeartBubbleScene alloc] initWithSize:self.heartBubbleView.frame.size];
[self.heartBubblesScene setScaleMode:SKSceneScaleModeFill];
self.heartBubblesScene.backgroundColor = [UIColor clearColor];

self.heartBubbleView.allowsTransparency = YES;
```

instead of

``` obj-c
self.heartBubblesScene = [[CBDHeartBubbleScene alloc] init];
```
